FROM node:10.16.3-alpine as builder
RUN apk add --update --no-cache \
    ca-certificates \
    openssl \
    g++ \
    gcc \
    libc-dev \
    make \
    patch \
    imagemagick \
  && rm -rf /var/cache/apk/*
ADD package.json /app/package.json
ADD package-lock.json /app/package-lock.json
WORKDIR /app
RUN npm install
ADD . /app
RUN npm run build

FROM nginx:1.17.3-alpine
COPY --from=builder /app/build /usr/share/nginx/html
